stages:
  - stage: 'code_check'
    condition: not(startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    displayName: 'code check (style/quality)'
    jobs:
      - job: 'style_golangci_lint'
        displayName: 'style:golangci-lint'
        steps:
          - task: 'GoTool@0'
            inputs:
              version: '1.22.0'
          - script: |
              sudo apt-get update && \
              sudo apt-get install -y python3 python3-yaml # for golangci-lint config merging
          - template: '../../../global/abstracts/scripts-repo.yaml'
          - script: $(Scripts.Directory)/global/scripts/golangci-lint/run.sh
        continueOnError: true
