include:
  - remote: 'https://raw.githubusercontent.com/rios0rios0/pipelines/main/gitlab/java/abstracts/gradle-application.yaml'
  - remote: 'https://raw.githubusercontent.com/rios0rios0/pipelines/main/gitlab/java/stages/20-security/gradle.yaml'

variables:
  PREFIX: ''
  # Increase the available memory for Java to avoid Out-of-Memory error in security step
  GRADLE_OPTS: '-Xmx2g'

.dependency-check:
  extends: '.gradle-application'
  cache:
    paths:
      - '.gradle'
      - '.gradle-home/caches'
      - '.gradle-home/notifications'
      - '.owasp'
      - 'build'
      - 'buildSrc/.gradle'
      - 'buildSrc/build'
