on:
  workflow_call:

runs:
  using: 'composite'
  steps:
    - uses: 'actions/checkout@v3'
    - uses: 'rios0rios0/pipelines/github/golang/abstracts/scripts-repo@feat/#19'
    - run: $SCRIPTS_DIR/global/scripts/gitleaks/run.sh
      shell: 'bash'
