on:
  workflow_call:

runs:
  using: 'composite'
  steps:
    - name: 'load'
      uses: 'actions/checkout@v4'
    - name: 'set context'
      uses: 'rios0rios0/pipelines/github/golang/abstracts/scripts-repo@main'
    - name: 'execute'
      shell: 'bash'
      run: $SCRIPTS_DIR/global/scripts/gitleaks/run.sh
    - name: 'upload'
      uses: 'actions/upload-artifact@v4'
      with:
        name: 'gitleaks'
        path: 'build/reports/gitleaks.json'
        if-no-files-found: 'error'
        overwrite: 'true'
        retention-days: 10
      if: always()
