on:
  workflow_call:

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: 'actions/checkout@v3'
    - name: Setup the scripts repository
      uses: 'rios0rios0/pipelines/github/golang/abstracts/scripts-repo@main'
    - name: Run Gitleaks
      shell: 'bash'
      run: $SCRIPTS_DIR/global/scripts/gitleaks/run.sh
    - name: Upload artifacts
      uses: 'actions/upload-artifact@v4'
      with:
        name: 'gitleaks'
        path: 'build/reports/gitleaks.json'
        if-no-files-found: 'error'
        overwrite: 'true'
        retention-days: 10
      if: always()
