on:
  workflow_call:

runs:
  using: 'composite'
  steps:
    - uses: 'actions/checkout@v3'
    - uses: 'rios0rios0/pipelines/github/golang/abstracts/scripts-repo@feat/#19'

    - uses: actions/github-script@v7
      id: get_check_runs
      with:
        script: |
          const { data: prData } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          });
          const { data: checkRunsData } = await github.rest.checks.listForRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: prData.head.sha
          });
          const checkRun = checkRunsData.check_runs.find(run => run.name.includes('golangci-lint'));
          return checkRun.id;

    - id: 'golangci_lint'
      run: $SCRIPTS_DIR/global/scripts/golangci-lint/run.sh || echo "EXIT_CODE=$?" >> $GITHUB_ENV && exit $EXIT_CODE
      shell: 'bash'
      continue-on-error: true

    - uses: 'LouisBrunner/checks-action@v2.0.0'
      with:
        #name: 'golangci-lint'
        check_id: '${{ steps.get_check_runs.outputs.result }}'
        token: '${{ github.token }}'
        conclusion: "${{ env.EXIT_CODE != 0 && 'failure' || 'success' }}"
        output: |
          {"title":"there are issues in the code (${{ env.EXIT_CODE }}) :x:", "summary":"Please fix the issues in the code", "text":"bbbb"}
