on:
  workflow_call:

runs:
  using: 'composite'
  outputs:
    upload_url: ${{ steps.create_release.outputs.upload_url }}
  steps:
    - id: 'create_release'
      uses: 'softprops/action-gh-release@v1'
      with:
        draft: false
        prerelease: false
        name: '${{ github.ref[10:] }}'
        tag_name: '${{ github.ref[10:] }}'
