on:
  workflow_call:

inputs:
  semgrep_lang:
    description: 'Sempgrep language to be used as default source'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: 'actions/checkout@v4'
    - name: Setup the scripts repository
      uses: 'rios0rios0/pipelines/github/golang/abstracts/scripts-repo@main'
    - name: Run Semgrep
      shell: 'bash'
      run: $SCRIPTS_DIR/global/scripts/semgrep/run.sh "${{ inputs.semgrep_lang }}"
    - name: Upload artifacts
      uses: 'actions/upload-artifact@v4'
      with:
        name: 'semgrep'
        path: 'build/reports/semgrep.json'
        if-no-files-found: 'error'
        overwrite: 'true'
        retention-days: 10
      if: always()
