stages:
  - stage: 'tests'
    condition: not(startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    displayName: 'tests'
    jobs:
      - job: 'test_all'
        displayName: 'test:all'
        steps:
          - task: 'GoTool@0'
            inputs:
              version: '1.23.1'
          - template: '../../../global/abstracts/scripts-repo.yaml'
          - script: $(Scripts.Directory)/global/scripts/golang/test/run.sh
