stages:
  - stage: 'security'
    condition: not(startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    displayName: 'security (sca/sast)'
    jobs:
      - template: '../../../global/stages/20-security/docker.yaml'
        parameters:
          SEMGREP_LANGUAGE: 'golang'
      # TODO: another Go security job
