on:
  workflow_call:

jobs:
  go:
    uses: 'rios0rios0/pipelines/.github/workflows/go.yaml@main'

  # fourth stage
  delivery-release:
    name: 'delivery > release'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'rios0rios0/pipelines/github/global/stages/40-delivery/release@main'
    needs: [ 'go' ]
    if: "github.event_name == 'push' && github.ref == 'refs/heads/main' && (contains(github.event.workflow_run.head_commit.message, 'origin/chore/bump-') && contains(github.event.workflow_run.head_commit.message, 'chore(bump)'))"

  delivery-binary:
    name: 'delivery > binary'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'rios0rios0/pipelines/github/global/stages/40-delivery/deb-releaser@main'
    needs: [ 'delivery-release' ]
    if: "(github.event_name == 'push' && github.ref == 'refs/heads/main') || startsWith(github.ref, 'refs/tags/')"
