on:
  workflow_call:

jobs:
  go:
    uses: 'rios0rios0/pipelines/.github/workflows/go.yaml@main'

  # fourth stage
  delivery-binary:
    name: 'delivery > binary'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'rios0rios0/pipelines/github/global/stages/40-delivery/binary@main'
        with:
          binary_name: '${{ env.BINARY_NAME }}'
    needs: [ 'go' ]
    if: "startsWith(github.ref, 'refs/tags/')"
