# see the bottom of the file for more information¹
# the parent workflow is responsible for setting up the call events²
on:
  workflow_call:

# it wasn't needed to set up anything for GoLang because 'ubuntu-latest' has all dependencies
jobs:
  # TODO: everything from the other file + fifth stage

  # fifth stage
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'rios0rios0/pipelines/github/global/stages/40-delivery/deb-releaser@feat/#19'
    needs: [ 'tests-test_all' ]
    if: "(github.event_name == 'push' && github.ref == 'refs/heads/main') || startsWith(github.ref, 'refs/tags/')"


# 1 - this file MUST be inside ".github/workflows" because of GitHub Actions limitations
# 2- the recommended events to trigger this work flow are:
#on:
#  push:
#    branches:
#      - 'main'
#    tags:
#      - '*'
#  pull_request:
#    branches:
#      - 'main'
#  workflow_dispatch:
